version: '3.6'
services:
 # Core Services
  router:
    extends:
      file: ./services/router/router.yml
      service: enabled
    depends_on:
      - mailer
      - main
  db:
    image: mysql:8.4.2-oracle
    platform: linux/arm64
    restart: always
    command: --mysql-native-password=ON
    volumes:
        # - ./init.sql:/docker-entrypoint-initdb.d/1.sql
        - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: projecsend
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
  mailer:
    extends:
      file: ./services/mailer.yml
      service: $MAILER
  main:
    extends:
      file: ./services/main.yml
      service: $PROJECTSEND
  phpmyadmin:
    extends:
      file: ./services/phpmyadmin.yml
      service: $PHPMYADMIN

volumes:
  db_data:
  node_data:
