version: '3.6'
services:
 # Core Services
  router:
    extends:
      file: ./services/router/router.yml
      service: enabled
    depends_on:
      - mailer
      - main
  db:
    image: mysql:5.7
    restart: always
    command: --disable-partition-engine-check
    volumes:
        #- ./init.sql:/data/application/init.sql
        - ./init.sql:/docker-entrypoint-initdb.d/1.sql
        - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_ROOT_HOST: '%'
  mailer:
    extends:
      file: ./services/mailer.yml
      service: $MAILER
  main:
    extends:
      file: ./services/main.yml
      service: $PROJECTSEND
  phpmyadmin:
    extends:
      file: ./services/phpmyadmin.yml
      service: $PHPMYADMIN

  ldap:
    extends:
      file: ./services/ldap/ldap.yml
      service: $LDAP
  ldap-ui:
    extends:
      file: ./services/ldap/ldap-ui.yml
      service: $LDAP
  openldap-ui:
    image: wheelybird/ldap-user-manager:v1.10
    container_name: openldap-ui
    environment:
      - LDAP_ADMIN_BIND_DN=cn=Admin,dc=flintstones,dc=com
      - LDAP_URI=ldap://ldap
      - LDAP_BASE_DN=dc=flintstones,dc=com
      - LDAP_REQUIRE_STARTTLS=FALSE
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_PWD=bedrock
      - LDAP_IGNORE_CERT_ERRORS=true
      - NO_HTTPS=TRUE
      - PASSWORD_HASH=SSHA
      - SERVER_HOSTNAME=localhost:18080
    depends_on:
      - ldap
    ports:
      - 18080:80
volumes:
  db_data:
  node_data:
