services:
  enabled:
    build:
      context: '.'
    env_file:
      - ../../shared.env
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        aliases:
          - main.app.local
          - mailer.app.local

    volumes:
      - ../../../ProjectSend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      #- ../custom_errors/:/var/www
      - node_data:/var/www/html/node_modules/
